[2022-06-21 19:58:40,147] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_marketvol.make_dir_1 scheduled__2022-06-20T18:30:00+00:00 [queued]>
[2022-06-21 19:58:40,160] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: d_marketvol.make_dir_1 scheduled__2022-06-20T18:30:00+00:00 [queued]>
[2022-06-21 19:58:40,160] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 19:58:40,160] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2022-06-21 19:58:40,160] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-21 19:58:40,190] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): make_dir_1> on 2022-06-20 18:30:00+00:00
[2022-06-21 19:58:40,195] {standard_task_runner.py:52} INFO - Started process 4158 to run task
[2022-06-21 19:58:40,199] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'd_marketvol', 'make_dir_1', 'scheduled__2022-06-20T18:30:00+00:00', '--job-id', '717', '--raw', '--subdir', 'DAGS_FOLDER/d_marketvol.py', '--cfg-path', '/tmp/tmp5is5qzvd', '--error-file', '/tmp/tmpdflrqgid']
[2022-06-21 19:58:40,200] {standard_task_runner.py:80} INFO - Job 717: Subtask make_dir_1
[2022-06-21 19:58:40,277] {task_command.py:370} INFO - Running <TaskInstance: d_marketvol.make_dir_1 scheduled__2022-06-20T18:30:00+00:00 [running]> on host 208c06f6f3c7
[2022-06-21 19:58:40,409] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=d_marketvol
AIRFLOW_CTX_TASK_ID=make_dir_1
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T18:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-20T18:30:00+00:00
[2022-06-21 19:58:40,412] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-21 19:58:40,414] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'bash /opt/***/dags/cr_folder.sh ']
[2022-06-21 19:58:40,431] {subprocess.py:85} INFO - Output:
[2022-06-21 19:58:40,476] {subprocess.py:92} INFO - /tmp/data/20220621
[2022-06-21 19:58:40,476] {subprocess.py:92} INFO - /tmp/data/20220621
[2022-06-21 19:58:40,480] {subprocess.py:92} INFO - rmdir: failed to remove '/tmp/data/20220621': No such file or directory
[2022-06-21 19:58:40,493] {subprocess.py:92} INFO - mkdir: cannot create directory ‘/tmp/data/20220621’: File exists
[2022-06-21 19:58:40,494] {subprocess.py:96} INFO - Command exited with return code 1
[2022-06-21 19:58:40,519] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-06-21 19:58:40,543] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=d_marketvol, task_id=make_dir_1, execution_date=20220620T183000, start_date=20220621T195840, end_date=20220621T195840
[2022-06-21 19:58:40,576] {standard_task_runner.py:97} ERROR - Failed to execute job 717 for task make_dir_1 (Bash command failed. The command returned a non-zero exit code 1.; 4158)
[2022-06-21 19:58:40,616] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-21 19:58:40,694] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
